import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, CircleCheck, Gauge, Lightbulb, Quote, Target, Workflow } from "lucide-react";
import { BookingLink } from "@/components/booking-link";
import { BlogCard, ConsultationCTA, Eyebrow, SectionHeading, ServiceGrid } from "@/components/shared";
import { posts, siteConfig } from "@/lib/site-content";
export default function Home() {
  const personSchema = { "@context": "https://schema.org", "@type": "Person", name: siteConfig.name, jobTitle: siteConfig.title, url: siteConfig.url, description: siteConfig.description };
  return <main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }} />
    <section className="relative overflow-hidden bg-slate-950 text-white"><Image src="/ai-growth-hero.jpg" alt="Abstract rising data pathways representing connected marketing growth" fill priority sizes="100vw" className="object-cover object-center opacity-50" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/95 to-slate-950/30" /><div className="container-shell relative grid min-h-[720px] items-center py-20 lg:grid-cols-[1.1fr_.9fr]"><div className="max-w-3xl"><Eyebrow>AI strategy. Human clarity. Real growth.</Eyebrow><h1 className="mt-7 text-5xl font-bold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Turn smarter marketing into <span className="text-blue-400">sustainable growth.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">I help small and medium-sized businesses generate better leads, attract more customers, and improve sales using practical AI and proven digital marketing strategy.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><BookingLink className="justify-center" /><Link href="/services" className="button-secondary justify-center border-white/20 bg-white/10 text-white hover:bg-white/15">Explore My Services <ArrowRight className="h-4 w-4" /></Link></div><p className="mt-5 flex items-center gap-2 text-sm text-slate-400"><CircleCheck className="h-4 w-4 text-cyan-400" />No-pressure call. Leave with practical recommendations and a customized plan.</p></div><div className="hidden lg:block" aria-hidden="true"><div className="ml-auto w-72 rounded-2xl border border-white/15 bg-slate-900/70 p-5 shadow-2xl backdrop-blur"><div className="mb-5 flex items-center justify-between text-xs font-bold uppercase tracking-widest text-slate-400"><span>Growth system</span><span className="text-cyan-400">Connected</span></div>{["Right audience", "Qualified leads", "Better conversion", "Scalable follow-up"].map((item, i) => <div key={item} className="mb-3 flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-500/20 text-xs font-bold text-blue-300">{i + 1}</span><span className="text-sm font-semibold">{item}</span></div>)}</div></div></div></section>
    <section className="border-b border-slate-200 bg-white"><div className="container-shell grid gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{[[Target, "Focused strategy", "Built around your goals"], [Gauge, "Data-informed", "Decisions over guesswork"], [Workflow, "Practical systems", "Designed for your team"], [Lightbulb, "Clear guidance", "No unnecessary jargon"]].map(([Icon, title, text]) => { const I = Icon as typeof Target; return <div key={title as string} className="flex gap-4 bg-white px-5 py-7"><I className="h-5 w-5 shrink-0 text-blue-600" /><div><p className="font-bold text-slate-950">{title as string}</p><p className="mt-1 text-sm text-slate-500">{text as string}</p></div></div>; })}</div></section>
    <section className="section-pad bg-slate-50"><div className="container-shell grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-start"><SectionHeading eyebrow="The real challenge" title="Is your marketing working hard—or just keeping you busy?" text="Growth becomes difficult when channels, tools, and activities are not connected to a clear customer journey." /><div className="grid gap-3 sm:grid-cols-2">{["Not enough qualified leads", "Marketing spend without clear results", "Inconsistent customer acquisition", "Too many confusing AI tools", "Time lost to repetitive tasks", "Traffic that does not convert", "Disconnected channels and data", "Slow or inconsistent follow-up"].map((problem) => <div key={problem} className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-700"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-blue-500" />{problem}</div>)}</div></div></section>
    <section className="section-pad"><div className="container-shell"><SectionHeading eyebrow="How I help" title="A connected marketing system—not another pile of tools." text="We focus AI and digital marketing on the parts of your business that create value: reaching the right people, starting better conversations, improving conversion, and learning what works." /><ServiceGrid limit={6} /><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/services" className="button-secondary justify-center">View All Services <ArrowRight className="h-4 w-4" /></Link><BookingLink className="justify-center" /></div></div></section>
    <section className="section-pad bg-slate-950 text-white"><div className="container-shell"><SectionHeading inverse eyebrow="A simple process" title="From marketing questions to a focused growth plan." text="The consultation is designed to be useful on its own. We clarify the situation, identify the strongest opportunities, and map practical next steps." /><div className="mt-12 grid gap-6 md:grid-cols-3">{[["01", "Book your free consultation", "Choose a convenient time and share a little context about your business."], ["02", "Business & marketing analysis", "We examine your goals, current strategy, bottlenecks, and customer journey."], ["03", "Get your customized plan", "Leave with prioritized recommendations you can begin implementing immediately."]].map(([number, title, text]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-sm font-black tracking-widest text-blue-400">{number}</span><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></div>)}</div></div></section>
    <section className="section-pad bg-blue-50"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[470px] overflow-hidden rounded-[2rem] bg-slate-900 p-8 text-white shadow-xl"><div className="metric-grid absolute inset-0 opacity-40" /><div className="relative flex h-full flex-col justify-between"><div><Eyebrow>Personal expert partnership</Eyebrow><p className="mt-8 max-w-md text-3xl font-bold leading-tight tracking-tight">Strategy first. Technology where it helps. Clear actions throughout.</p></div><div className="mt-20 grid grid-cols-2 gap-3">{["AI + marketing expertise", "Plain-language guidance", "Customized strategy", "Measurable priorities"].map((item) => <div key={item} className="rounded-xl border border-white/10 bg-white/5 p-4 text-sm font-semibold"><Check className="mb-3 h-4 w-4 text-cyan-400" />{item}</div>)}</div></div></div><div><SectionHeading eyebrow="Why work with me" title="Modern marketing expertise, translated into practical business decisions." text="You work directly with an expert who connects strategy, customer insight, technology, and measurement. Recommendations are shaped around your business—not a pre-built agency package." /><div className="mt-8"><Link href="/about" className="button-secondary">Learn More About Me <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
    <section className="section-pad"><div className="container-shell"><SectionHeading eyebrow="Proof, when it is ready" title="A foundation for credible case studies—not invented claims." text="This section is ready for verified client stories and can stay hidden until real results, approvals, and testimonials are available." /><div className="mt-10 grid gap-5 md:grid-cols-3">{["Client & challenge", "Strategy & execution", "Verified outcome"].map((title) => <div key={title} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6"><span className="text-xs font-bold uppercase tracking-wider text-slate-400">Case study placeholder</span><h3 className="mt-6 font-bold text-slate-800">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">Verified details will be added here after client approval.</p></div>)}</div></div></section>
    <section className="section-pad bg-slate-950 text-white"><div className="container-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><Eyebrow>Client feedback</Eyebrow><h2 className="mt-5 text-4xl font-bold tracking-tight">Real words will matter more than manufactured praise.</h2><p className="mt-5 leading-7 text-slate-400">This testimonial area is ready for approved client feedback. Until then, it is transparent about what is still to come.</p></div><div className="rounded-3xl border border-white/10 bg-white/5 p-8"><Quote className="h-8 w-8 text-blue-400" /><blockquote className="mt-8 text-2xl font-semibold leading-relaxed text-slate-200">“Client testimonial will be added here after approval.”</blockquote><div className="mt-8 border-t border-white/10 pt-5 text-sm text-slate-500"><span className="font-bold text-slate-300">Client name</span> · Position · Company · Photo placeholder</div></div></div></section>
    <section className="section-pad border-y border-slate-200 bg-slate-50"><div className="container-shell"><SectionHeading eyebrow="Latest insights" title="Practical thinking for smarter growth." text="Clear guidance on AI, lead generation, automation, conversion, and the marketing decisions that connect them." /><div className="mt-10 grid gap-6 md:grid-cols-3">{posts.slice(0, 3).map((post) => <BlogCard key={post.slug} post={post} />)}</div><div className="mt-10"><Link href="/blog" className="button-secondary">View All Articles <ArrowRight className="h-4 w-4" /></Link></div></div></section><ConsultationCTA />
  </main>;
}
