"use client";
import { useState } from "react";
import { AlertCircle, CheckCircle2, Loader2 } from "lucide-react";
type Errors = Partial<Record<"name" | "email" | "need" | "message", string>>;
export function ContactForm() {
  const [errors, setErrors] = useState<Errors>({}); const [status, setStatus] = useState<"idle" | "loading" | "demo">("idle");
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const next: Errors = {}; if (!String(data.get("name") || "").trim()) next.name = "Please enter your name."; if (!/^\S+@\S+\.\S+$/.test(String(data.get("email") || ""))) next.email = "Enter a valid email address."; if (!String(data.get("need") || "")) next.need = "Choose the area you need help with."; if (String(data.get("message") || "").trim().length < 20) next.message = "Please add at least 20 characters."; setErrors(next); if (Object.keys(next).length) return; setStatus("loading"); window.setTimeout(() => setStatus("demo"), 500); }
  const field = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-base text-slate-950 outline-none transition placeholder:text-slate-400 focus:border-blue-600 focus:ring-4 focus:ring-blue-100";
  return <form onSubmit={submit} noValidate className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8" data-event="contact_form_submit"><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" htmlFor="name" error={errors.name}><input id="name" name="name" autoComplete="name" className={field} aria-invalid={!!errors.name} /></Field><Field label="Email" htmlFor="email" error={errors.email}><input id="email" name="email" type="email" autoComplete="email" className={field} aria-invalid={!!errors.email} /></Field><Field label="Phone (optional)" htmlFor="phone"><input id="phone" name="phone" type="tel" autoComplete="tel" className={field} /></Field><Field label="Business name" htmlFor="company"><input id="company" name="company" autoComplete="organization" className={field} /></Field><Field label="Website (optional)" htmlFor="website"><input id="website" name="website" type="url" placeholder="https://" className={field} /></Field><Field label="What do you need help with?" htmlFor="need" error={errors.need}><select id="need" name="need" defaultValue="" className={field} aria-invalid={!!errors.need}><option value="" disabled>Select an area</option><option>AI marketing strategy</option><option>Lead generation</option><option>Marketing automation</option><option>Content and SEO</option><option>Conversion optimization</option><option>Not sure yet</option></select></Field></div><div className="mt-5"><Field label="Tell me about your goals" htmlFor="message" error={errors.message}><textarea id="message" name="message" rows={5} className={field} placeholder="What would you like your marketing to achieve?" aria-invalid={!!errors.message} /></Field></div><div className="hidden" aria-hidden="true"><label htmlFor="company-url">Leave this field empty</label><input id="company-url" name="company-url" tabIndex={-1} autoComplete="off" /></div><button type="submit" disabled={status === "loading"} className="button-primary mt-6 w-full justify-center sm:w-auto">{status === "loading" ? <><Loader2 className="h-4 w-4 animate-spin" />Checking details…</> : "Send Consultation Request"}</button><p className="mt-4 text-sm leading-6 text-slate-500">This form is in preview mode and does not send email yet. Connect your preferred form or email provider before launch.</p>{status === "demo" && <div className="mt-5 flex gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-900" role="status"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0" />Your details are valid. Connect a form provider to enable delivery.</div>}</form>;
}
function Field({ label, htmlFor, error, children }: { label: string; htmlFor: string; error?: string; children: React.ReactNode }) { return <div><label htmlFor={htmlFor} className="text-sm font-bold text-slate-800">{label}</label>{children}{error && <p className="mt-2 flex items-center gap-1.5 text-sm font-medium text-red-700"><AlertCircle className="h-4 w-4" />{error}</p>}</div>; }
