import Link from "next/link";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { BookingLink } from "@/components/booking-link";
import { services, type Post } from "@/lib/site-content";
export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-blue-500" />{children}</p>; }
export function SectionHeading({ eyebrow, title, text, centered = false, inverse = false }: { eyebrow: string; title: string; text?: string; centered?: boolean; inverse?: boolean }) { return <div className={centered ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}><div className={centered ? "flex justify-center" : ""}><Eyebrow>{eyebrow}</Eyebrow></div><h2 className={`section-title mt-5 ${inverse ? "!text-white" : ""}`}>{title}</h2>{text && <p className={`section-copy mt-5 ${inverse ? "!text-slate-300" : ""}`}>{text}</p>}</div>; }
export function ConsultationCTA({ title = "Ready to grow with smarter marketing?", text = "Book a free consultation to identify your strongest opportunities and leave with practical next steps for your business." }: { title?: string; text?: string }) { return <section className="section-pad"><div className="container-shell"><div className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-12 text-white shadow-2xl sm:px-12 md:py-16"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-blue-500/20 blur-3xl" /><div className="relative grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><Eyebrow>Free growth consultation</Eyebrow><h2 className="mt-5 max-w-3xl text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">{text}</p><p className="mt-4 flex items-center gap-2 text-sm font-semibold text-blue-200"><Check className="h-4 w-4" />Includes actionable recommendations and a customized marketing plan.</p></div><BookingLink className="justify-center bg-white text-slate-950 hover:bg-blue-50" /></div></div></div></section>; }
export function ServiceGrid({ limit }: { limit?: number }) { return <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.slice(0, limit).map((service, index) => { const Icon = service.icon; return <article key={service.slug} className="card group"><div className="mb-8 flex items-start justify-between"><span className="icon-box"><Icon className="h-5 w-5" /></span><span className="text-xs font-bold text-slate-300">{String(index + 1).padStart(2, "0")}</span></div><h3 className="text-xl font-bold tracking-tight text-slate-950">{service.title}</h3><p className="mt-3 leading-7 text-slate-600">{service.summary}</p><Link href={`/services#${service.slug}`} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Learn more <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></article>; })}</div>; }
export function BlogCard({ post }: { post: Post }) { return <article className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Link href={`/blog/${post.slug}`} className={`block h-44 bg-gradient-to-br ${post.accent} p-6`} aria-label={`Read ${post.title}`}><div className="flex h-full items-end justify-between"><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-white backdrop-blur">{post.category}</span><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-slate-950"><ChevronRight className="h-5 w-5" /></span></div></Link><div className="p-6"><div className="flex gap-3 text-xs font-medium text-slate-500"><span>{post.date}</span><span>•</span><span>{post.readTime}</span></div><h3 className="mt-3 text-xl font-bold leading-snug tracking-tight text-slate-950"><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3><p className="mt-3 leading-7 text-slate-600">{post.excerpt}</p><Link href={`/blog/${post.slug}`} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Read article <ArrowRight className="h-4 w-4" /></Link></div></article>; }
export function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="hero-grid border-b border-slate-200 bg-slate-50"><div className="container-shell py-20 sm:py-24"><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-6 max-w-4xl text-4xl font-bold tracking-[-0.04em] text-slate-950 sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{text}</p></div></section>; }
