import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Clock3 } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { ConsultationCTA } from "@/components/consultation-cta";
import { BlogCard } from "@/components/blog-card";
import { getPost, posts } from "@/data/posts";
import { siteConfig } from "@/lib/site-config";

export function generateStaticParams(){return posts.map(post=>({slug:post.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const post=getPost(slug);if(!post)return{};return{title:post.title,description:post.excerpt,alternates:{canonical:`/blog/${post.slug}`},openGraph:{type:"article",title:post.title,description:post.excerpt,url:`/blog/${post.slug}`,publishedTime:post.date},twitter:{card:"summary_large_image",title:post.title,description:post.excerpt}}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=getPost(slug);if(!post)notFound();const related=posts.filter(item=>item.slug!==post.slug).slice(0,2);const jsonLd={"@context":"https://schema.org","@type":"BlogPosting",headline:post.title,description:post.excerpt,datePublished:post.date,author:{"@type":"Person",name:"Sithar"},publisher:{"@type":"Person",name:"Sithar"},mainEntityOfPage:`${siteConfig.url}/blog/${post.slug}`};return <main><article className="article"><header className="article-header site-container"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Blog",href:"/blog"},{label:post.title}]}/><div className="article-kicker"><span>{post.category}</span><span><Clock3 size={15}/>{post.readingTime}</span></div><h1>{post.title}</h1><p>{post.excerpt}</p><div className="article-byline"><div className="mini-avatar">S</div><div><strong>By Sithar</strong><time dateTime={post.date}>Published {post.displayDate}</time></div></div></header><div className="article-feature site-container">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={post.image} alt={post.imageAlt} width="1200" height="800" decoding="async"/></div><div className="article-layout site-container"><aside><p>IN THIS ARTICLE</p>{post.sections.map((section,index)=><a href={`#section-${index+1}`} key={section.heading}>{section.heading}</a>)}</aside><div className="article-content">{post.sections.map((section,index)=><section id={`section-${index+1}`} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.points&&<ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul>}</section>)}<div className="author-box"><div className="mini-avatar large">S</div><div><p className="eyebrow">ABOUT THE AUTHOR</p><h3>Sithar</h3><p>Dentist passionate about dental outreach, accessible oral healthcare, purposeful learning, and sharing useful lessons with others.</p></div></div><Link className="text-link" href="/blog"><ArrowLeft size={17}/>Back to all articles</Link></div></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/></article><section className="section related-section"><div className="site-container"><div className="split-heading"><p className="eyebrow">KEEP READING</p><h2>Related articles</h2></div><div className="blog-grid blog-grid-two">{related.map(item=><BlogCard key={item.slug} post={item}/>)}</div></div></section><ConsultationCTA compact/></main>}
