import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { ConsultationCTA } from "@/components/shared";
import { ShareActions } from "@/components/share-actions";
import { posts, siteConfig } from "@/lib/site-content";
export function generateStaticParams() { return posts.map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = posts.find((item) => item.slug === slug); if (!post) return {}; return { title: post.title, description: post.excerpt, alternates: { canonical: `/blog/${slug}` }, openGraph: { title: post.title, description: post.excerpt, type: "article" } }; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = posts.find((item) => item.slug === slug); if (!post) notFound(); const articleSchema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.excerpt, datePublished: post.isoDate, author: { "@type": "Person", name: siteConfig.name }, mainEntityOfPage: `${siteConfig.url}/blog/${post.slug}` }; return <main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><article><header className={`bg-gradient-to-br ${post.accent} text-white`}><div className="container-shell py-20 sm:py-28"><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-bold text-white/80"><ArrowLeft className="h-4 w-4" />Back to insights</Link><p className="mt-12 text-sm font-bold uppercase tracking-widest text-white/70">{post.category}</p><h1 className="mt-5 max-w-5xl text-4xl font-bold leading-tight tracking-[-.045em] sm:text-6xl">{post.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/80">{post.excerpt}</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-semibold text-white/75"><span>{siteConfig.name}</span><span>•</span><span>{post.date}</span><span>•</span><span>{post.readTime}</span></div></div></header><div className="container-shell grid gap-12 py-16 lg:grid-cols-[230px_minmax(0,720px)] lg:justify-center"><aside className="lg:sticky lg:top-28 lg:self-start"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">In this article</p><nav className="mt-4 flex flex-col gap-3 text-sm font-semibold text-slate-600">{post.sections.map((section, i) => <a key={section.heading} href={`#section-${i}`}>{section.heading}</a>)}</nav><ShareActions title={post.title} /></aside><div>{post.sections.map((section, i) => <section key={section.heading} id={`section-${i}`} className="mb-12 scroll-mt-28"><h2 className="text-3xl font-bold tracking-tight text-slate-950">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-5 text-lg leading-8 text-slate-600">{paragraph}</p>)}</section>)}</div></div></article><ConsultationCTA /></main>; }
